name: Codebase tests

on:
  pull_request:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XLA_FLAGS: --xla_gpu_enable_command_buffer=
  XLA_PYTHON_CLIENT_PREALLOCATE: false
  XLA_PYTHON_CLIENT_ALLOCATOR: platform

jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-22.04, ParallelHoss]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3

      - name: Install nox-poetry
        run: pip install nox-poetry

      - name: Cache Nox environments
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-${{ matrix.runner }}-nox-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.runner }}-nox

      - name: Run Tests
        run: nox -r -s tests -- ${{ matrix.runner == 'ParallelHoss' && 'cuda12' || 'cpu' }}
