name: safety

on:
  pull_request:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  safety:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3

      - name: Install poetry-plugin-export
        run: poetry self add poetry-plugin-export

      - name: Install poetry/nox-poetry
        run: pip install nox-poetry

      - name: Cache Nox environments
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-nox-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-nox

      - name: Run Nox
        run: nox -r -s safety
