name: Test mkdocs build

on:
  pull_request:

env:
  POETRY_EXPERIMENTAL_SYSTEM_GIT_CLIENT: true

permissions:
  contents: write
  pages: write

jobs:
  build-docs:
    runs-on: DocsBuilder

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # This works via GitHub's "deploy keys". This repo has a secret set up
      # with the private key, and the mkdocs-material-insiders clone in the
      # library has the public key set as a deploy key.
      - name: Configure SSH key for mkdocs-material-insiders
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.MKDOCSTRINGS_PYTHON_SSH_KEY }}
            ${{ secrets.INSIDER_SSH_KEY }}

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3

      - name: Install poetry-plugin-export
        run: poetry self add poetry-plugin-export

      - name: Install nox-poetry
        run: pip install nox-poetry

      - name: Cache Nox environments
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-nox-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-nox

      - name: Run Docs Build
        run: nox -r -s docs-build
